baseurl: "/"
title: "Ahmed Ali"
page_load_js: "assets/js/main.js"
params:
  layout_style: overflow
  palette: blue
  header:
    title: "Ahmed Ali"
    tagline: "Software developer"
    profile_img: images/avatar.jpg
    bg: dark
    has_nav: true
    has_social: true
  footer:
    content: "Ahmed Ali&copy; All rights reserved."
    links:
      - text: "Home"
        url: https://ahmedali.me
        new_window: true
sass:
  input_file: sass/main.scss.njk
  output_file: assets/css/main.css
  indentWidth: 4
  outputStyle: nested
  precision: 10
