name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    name: deploy to github pages
    runs-on: ubuntu-latest

    steps:
    - name: GitHub Pages Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        EXTERNAL_REPOSITORY: ahmedali7o1/ahmedali7o1.github.io
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
