name: Deploy

on:
  push:
    branches: 
      - master

jobs:
  build:
    name: "deploy to github pages"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - run: npm run build

    - name: "GitHub Pages Deploy"
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        EXTERNAL_REPOSITORY: ahmedali7o1/ahmedali7o1.github.io
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
